### ISSUE TITLE
however this package itself specifies a main module field that could not be resolved styled-icon

### ISSUE THREAD

**Issue by pmapelli** [styled-icons/styled-icons#1414]
![image](https://user-images.githubusercontent.com/15129047/91343876-86813b80-e7b3-11ea-816e-5cc3e00bffd7.png)
![image](https://user-images.githubusercontent.com/15129047/91343973-a9135480-e7b3-11ea-9dcd-7247fe0b762b.png)

I'm having this error after installing the package.

I already removed the node_modules folder, but the error persists.

**Comment by jacobwgillespie** [comment]
Hey @pmapelli, thank you for this report! I have pushed a fix and it was just released as v10.18.0 - let me know if you run into any issues.
