### ISSUE TITLE
Fluent UI Icons

### ISSUE THREAD

**Issue by oliver92** [styled-icons/styled-icons#1611]
- Name: `Fluent UI`
- License: `https://github.com/microsoft/fluentui/blob/master/LICENSE`
- NPM package: `https://www.npmjs.com/package/@fluentui/react-icons`
- Website (if any): `https://developer.microsoft.com/en-us/fluentui?fabricVer=7#/styles/web/icons#available-icons`

**Comment by jacobwgillespie** [comment]
Hey @oliver92 thanks for opening this issue!

Do you know if the Fluent UI icons are available as SVGs? And out of curiosity, does using the `@fluentui/react-icons` package directly work for you, or are you looking for something it's missing? I can't find the SVG sources for the icons, which are necessary for adding them here, and there's already React components for Fluent UI.

**Comment by oliver92** [comment]
Oh, i was thinking of these icons. Sorry for the mistake

https://github.com/microsoft/fluentui-system-icons/blob/master/icons.md

**Comment by jacobwgillespie** [comment]
@oliver92 Sorry for the delay, but this has now been published as v10.30.0 🎉

**Comment by oliver92** [comment]
Awesome! Tnx
