### ISSUE TITLE
Error during of import during rendering

### ISSUE THREAD

**Issue by FelipeVash** [styled-icons/styled-icons#1671]
I´m getting this error menssage:

![image](https://user-images.githubusercontent.com/67391914/109828320-4942ae00-7c1b-11eb-8f58-630128283558.png)

Already tried every import option described at the Readme

**Comment by jacobwgillespie** [comment]
@FelipeVash That error doesn't say anything about Styled Icons, it's referring to the `pages/_document.js` file in your Next.js project.

If the problem appeared after adding Styled Icons, are you able to share a repo that demonstrates the problem? It can be your actual repo, or another one you create with a minimal reproduction. I'd be happy to take a look.

**Comment by FelipeVash** [comment]
@jacobwgillespie  Thank you so much for the fast response! Sorry for my noob issue, I was not able to find the exact error but I deleted the node_modules folder and the path at the package, reinstalled it all and it worked just fine.
I´m pretty new at react, once again, my bad.

**Comment by jacobwgillespie** [comment]
Cool, absolutely no problem - glad you figured it out! 🎉
