### ISSUE TITLE
Documentation fix

### ISSUE THREAD

**Issue by droplab** [styled-icons/styled-icons#1710]
Hi, thanks for a great library. Wanted to bring to your attention an issue that greatly impacted a project I've been working on (in a bad way).

If your import is structured as follows, **EVERY SINGLE ICON** in the collection will be imported into your project and **not cached**. We were seeing the entire icon collection being compiled on every route change and page render...

```javascript
import { ChevronBarLeft } from '@styled-icons/bootstrap'
```

Importing like this works as expected

```javascript
import { ChevronBarLeft } from '@styled-icons/bootstrap/ChevronBarLeft'
```
Cheers

**Comment by stramel** [comment]
@droplab This sounds like a problem with your app's tree-shaking setup. We have setup the library to be able to be tree-shaken using common bundlers. 

Can you provide some insight as to what you're using to bundle/tree-shake? Or even better provide a way to reproduce this issue?

**Comment by jacobwgillespie** [comment]
@droplab any additional details you can share about what kind of app / bundler you are using? Styled Icons should be working with most major bundlers, but if you're seeing an issue, I'm happy to take a look.

**Comment by jacobwgillespie** [comment]
I'm going to close this issue, but feel free to post back if you're able to reproduce and share any additional details!
