### ISSUE TITLE
StyledComponents logo error

### ISSUE THREAD

**Issue by leoo1995** [styled-icons/styled-icons#1825]
Hi, im trying to use the styledcomponents logo but the there is an error :

> "Module not found: Can't resolve '@styled-icons/simple-icons/StyledComponents' in '/home/luis/react/portfolio/src/components/Technologies'"

i use this package like that:
```
import { StyledComponents } from "@styled-icons/simple-icons/StyledComponents"
<StyledComponents/>
```

**Comment by jacobwgillespie** [comment]
@leoo1995 I believe there's a problem with the website deploying so it's currently out-of-date, I'll work on getting that fixed.

In the current version of the package, that icon is named `Styledcomponents` so if you import like this, it should work:

```js
import { Styledcomponents } from "@styled-icons/simple-icons/Styledcomponents"
<Styledcomponents/>
```

**Comment by leoo1995** [comment]
Thanks, it worked.
