### ISSUE TITLE
More compact website?

### ISSUE THREAD

**Issue by franciscop** [styled-icons/styled-icons#2010]
I'd like to suggest making the website layout more compact and more icons can be visible at once, maybe something like this?

<table>
  <tr><th>Before</th><th>After</th></tr>
  <tr>
    <td>
      <img width="500px" src="https://user-images.githubusercontent.com/2801252/165201497-f111eb32-906a-4ce9-b99d-1b328ae81bc1.png" />
    </td>
    <td>
      <img width="500px" src="https://user-images.githubusercontent.com/2801252/165201504-1eb9b1a1-bd5d-4def-a40e-34e792d92891.png" />
    </td>
  </tr>
</table>

Would be happy to help with a PR but haven't seen the website source files in this repo.

**Comment by jacobwgillespie** [comment]
Hey, thanks for the suggestion! If you'd like to send a PR, the website is here https://github.com/styled-icons/website, it would be appreciated! I may also take a look if I get some spare cycles beforehand too.

**Comment by franciscop** [comment]
Thanks! Sent a PR:

https://github.com/styled-icons/website/pull/55

**Comment by jacobwgillespie** [comment]
Nice this live - thank you again! 🎉
