### ISSUE TITLE
@styled-icons/styled-icon dependencies causing duplication due to older versions of @emotion/is-prop-valid

### ISSUE THREAD

**Issue by rockerBOO** [styled-icons/styled-icons#2081]
When used with styled-components, this causes a duplication of dependencies. When looking at the source for [styled-icons/packages/@styled-icons/styled-icon/package.json](https://github.com/styled-icons/styled-icons/blob/main/packages/%40styled-icons/styled-icon/package.json), I do not see this dependency. Could this be bumped or removed if not required?

```
 $ yarn why @emotion/is-prop-valid
├─ @styled-icons/styled-icon@npm:10.6.3 [a3d52]
│   └─ @emotion/is-prop-valid@npm:0.8.8 (via npm:^0.8.7)
└─ styled-components@npm:5.3.5 [f2288]
      └─ @emotion/is-prop-valid@npm:1.2.0 (via npm:^1.1.0)
```

I am specifically using ` "@styled-icons/feather": "^10.34.0",`.

Thank you

**Comment by jacobwgillespie** [comment]
Hey, thanks for the issue report, I've published a version bump for all packages that should remove that dependency, let me know if you run into any issues 👍

**Comment by rockerBOO** [comment]
Perfect! Thank you!
