### ISSUE TITLE
fa-solid 10.46 looks broken

### ISSUE THREAD

**Issue by znarf** [styled-icons/styled-icons#2108]
It seems the difference between @styled-icon/fa-solid 10.46 and 10.30 is huge. Many icons are missing, many added.

Was the build broken or any other reason for the change?

This was spotted by our CI here: https://github.com/opencollective/opencollective-frontend/pull/8178

I looked at the content of the package and could confirm something was odd:

<img width="636" alt="Screenshot 2022-12-21 at 17 55 48" src="https://user-images.githubusercontent.com/806/208961818-3e060905-38a6-47f6-99b2-5bb0ff4e6750.png">

**Comment by jacobwgillespie** [comment]
Hey, thanks for catching this, it should be fixed in v10.47.0 - looks like earlier this year FontAwesome changed how they name icons such that alternate names for icons stopped getting included here. I've fixed that and published the new version.

**Comment by znarf** [comment]
@jacobwgillespie Thank you! Looks good.
