### ISSUE TITLE
styled-icons.dev seems to be down

### ISSUE THREAD

**Issue by lxchurbakov** [styled-icons/styled-icons#2129]
## Description

Hey guys! Not an issue per se, just noticed and wanted to let you know your website is down. https://isitup.org/styled-icons.dev you need any help with that?

**Comment by jacobwgillespie** [comment]
Thanks for flagging, I've fixed the DNS nameservers, it should propagate the fix over the next 24 hours 👍

**Comment by jacobwgillespie** [comment]
The website is up again (at least for me, DNS can be slow). Thanks again!
