### ISSUE TITLE
Referring styled-icon in styled component breaks styles

### ISSUE THREAD

**Issue by vbartonicek** [styled-icons/styled-icons#676]
Passing styled-icon into styled components styles (https://www.styled-components.com/docs/advanced#referring-to-other-components) breaks styling of all styled components. 

Example:

```js
import { Comment } from 'styled-icons/octicons/Comment';

const CommentCount = styled.div`
    & ${Comment} {
        margin-right: 3px;
    }
`;

const ParentComponent= styled.div`
     background: lightblue;
`;

export const Something = () => (
   <ParentComponent>
       <Comment size="1.2em" />
       <CommentCount />
   </ParentComponent>
);
```

If I remove the CommentCount component it works as expected.

Workaround is to replace `${Comment}` with `svg`. 

The issue happens on local environment only, on production it seems it work as expected as far we have observed.

**Comment by StorytellerCZ** [comment]
Another caveat, when you open the component on the first time or refresh it works fine, but when you navigate away and back it is broken.

**Comment by jacobwgillespie** [comment]
@vbartonicek or @StorytellerCZ would either of you be able to create a repo to demonstrate this issue?  I tried to recreate with a CodeSandbox (https://codesandbox.io/s/jvjl0k49zw) but wasn't able to reproduce the behavior you're describing.  I'd be happy to take a look if I can get access to the bug.

**Comment by StorytellerCZ** [comment]
@jacobwgillespie I'll try to expand on your sample when I get some time. I think the critical thing will be the inclusion of a router or dynamic changes that are happening in our case.

**Comment by jacobwgillespie** [comment]
I haven't been able to reproduce this issue locally - I'm going to close this issue for now, but feel free to post back if you're able to share an isolated reproduction, I'd still be happy to take a look!

**Comment by seb-thomas** [comment]
I got this today too, sorry I dont have more details. 

I copied some code over from another project where I'm using CRA and styled-components/macro v5.2.1, and noticed this issue. It weirdly breaks unrelated selectors, it seems like they apply for a second then not. 

The same code does not have this issue on the CRA project - that I've noticed, although as OP says it's hard to pin down - so I thought updating SC would help, but did nothing. Maybe the /macro version is different?

Can send you a video if that helps, would just have to comment out some confidential stuff from app first

**Comment by jacobwgillespie** [comment]
Hey @seb-thomas, yeah probably the best thing you could send would be a repo reproducing the issue, it doesn't have to be your private repo, just a small example, maybe using the same dependency versions. Or if not possible, yeah feel free to send what you can. 👍

**Comment by jacobwgillespie** [comment]
@seb-thomas any updates here? Did you ever track down a cause or a reproduction?

**Comment by jacobwgillespie** [comment]
I'm going to close this issue, but feel free to let me know if you're still able to reproduce and are able to share!
